import { PartialType } from '@nestjs/swagger';
import { DatabaseModelFields } from '@server/libs/database';
import { PaginationQueryDto } from '@server/platform/dtos';
import { MultipleOrderBy, PropertyDto } from 'src/decorator';

// Auto generated by tools/generate-dtos.ts at 2025-12-22T10:12:02.299Z
// ****************************** Base PhraseRetry response dto ******************************
export class BasePhraseRetryResponseDto {
  @PropertyDto()
  id: number;

  @PropertyDto()
  phraseId: number;

  @PropertyDto()
  createdAt: Date;
}

// ****************************** GET PhraseRetry dto ******************************
export class GetPhraseRetryDetailResponseDto extends BasePhraseRetryResponseDto {
  // Add more fields if needed such as relations
}

export class GetPhraseRetryListResponseDto extends BasePhraseRetryResponseDto {
  // Add more fields if needed such as relations
}

export class GetPhraseRetryListQueryDto extends PaginationQueryDto {
  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  id: number;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  createdAtRangeStart: Date;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  createdAtRangeEnd: Date;

  @MultipleOrderBy(DatabaseModelFields.PhraseRetry)
  orderBy: string[];
}

// ****************************** CREATE PhraseRetry dto ******************************
export class CreatePhraseRetryBodyDto {
  @PropertyDto({
    type: Number,
    required: true,
    validated: true,
  })
  phraseId: number;
}

export class CreatePhraseRetryResponseDto extends BasePhraseRetryResponseDto {}

// ****************************** UPDATE PhraseRetry dto ******************************
export class UpdatePhraseRetryBodyDto extends PartialType(CreatePhraseRetryBodyDto) {}

export class UpdatePhraseRetryResponseDto extends BasePhraseRetryResponseDto {}

// ****************************** More PhraseRetry dto below ******************************
