import { OmitType, PartialType } from '@nestjs/swagger';
import { Languages } from '@prisma/client';
import { DatabaseModelFields } from '@server/libs/database';
import { PaginationQueryDto } from '@server/platform/dtos';
import { MultipleOrderBy, PropertyDto } from 'src/decorator';
import { CreateS3ObjectBodyDto } from 'src/module/storage/dtos';

// Auto generated by tools/generate-dtos.ts at 2025-10-12T14:01:22.379Z
// ****************************** Base PhraseAudio response dto ******************************
export class BasePhraseAudioResponseDto {
  @PropertyDto()
  id: number;

  @PropertyDto()
  phraseId: number;

  @PropertyDto()
  s3ObjectId: number;

  @PropertyDto()
  language: Languages;

  @PropertyDto()
  createdAt: Date;
}

// ****************************** GET PhraseAudio dto ******************************
export class GetPhraseAudioDetailResponseDto extends BasePhraseAudioResponseDto {
  // Add more fields if needed such as relations
}

export class GetPhraseAudioListResponseDto extends BasePhraseAudioResponseDto {
  // Add more fields if needed such as relations
}

export class GetPhraseAudioListQueryDto extends PaginationQueryDto {
  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  id: number;

  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  phraseId: number;

  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  s3ObjectId: number;

  @PropertyDto({
    type: Languages,
    required: false,
    validated: true,
    structure: 'enum',
  })
  language: Languages;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  createdAtRangeStart: Date;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  createdAtRangeEnd: Date;

  @MultipleOrderBy(DatabaseModelFields.PhraseAudio)
  orderBy: string[];
}

// ****************************** CREATE PhraseAudio dto ******************************
export class CreatePhraseAudioBodyDto {
  @PropertyDto({
    type: Number,
    required: true,
    validated: true,
  })
  phraseId: number;

  @PropertyDto({
    type: CreateS3ObjectBodyDto,
    required: true,
    validated: true,
    structure: 'dto',
  })
  s3Object: CreateS3ObjectBodyDto;

  @PropertyDto({
    type: Languages,
    required: false,
    validated: true,
    structure: 'enum',
  })
  language: Languages;
}

export class CreatePhraseAudioResponseDto extends BasePhraseAudioResponseDto {}

// ****************************** UPDATE PhraseAudio dto ******************************
export class UpdatePhraseAudioBodyDto extends PartialType(
  OmitType(CreatePhraseAudioBodyDto, ['s3Object', 'phraseId']),
) {}

export class UpdatePhraseAudioResponseDto extends BasePhraseAudioResponseDto {}

// ****************************** More PhraseAudio dto below ******************************
