export function getDtoContent(args: {
  moduleName: string;
  responseProperties: string;
  queryProperties: string;
  bodyProperties: string;
  importContent: string;
}) {
  const {
    moduleName,
    responseProperties,
    queryProperties,
    bodyProperties,
    importContent,
  } = args;

  return `import { PartialType } from '@nestjs/swagger';
${importContent}
import { PaginationMetadataResponseDto, PaginationQueryDto } from '@server/platform/dtos';
import { DatabaseModelFields } from '@server/libs/database';
import { MultipleOrderBy, PropertyDto } from 'src/decorator';

// Auto generated by tools/generate-dtos.ts at ${new Date().toISOString()}
// ****************************** BASE ${moduleName} RESPONSE ******************************
export class Base${moduleName}ResponseDto {
${responseProperties}
}

// ****************************** get${moduleName}Detail ******************************
export class Get${moduleName}DetailResponseDto extends Base${moduleName}ResponseDto {
  // Add more fields if needed such as relations
}

// ****************************** get${moduleName}List ******************************
export class Get${moduleName}ItemDto extends Base${moduleName}ResponseDto {
  // Add more fields if needed such as relations
}

export class Get${moduleName}ListResponseDto {
  @PropertyDto({
    type: Get${moduleName}ItemDto,
    structure: 'dtoArray',
  })
  items: Get${moduleName}ItemDto[];

  @PropertyDto({
    type: PaginationMetadataResponseDto,
    structure: 'dto',
  })
  pagination: PaginationMetadataResponseDto;
}

export class Get${moduleName}ListQueryDto extends PaginationQueryDto {
${queryProperties}
}

// ****************************** create${moduleName} ******************************
// todo: delete this line if you have corrected the dto
export class Create${moduleName}BodyDto {
${bodyProperties}
}

export class Create${moduleName}ResponseDto extends Base${moduleName}ResponseDto {}

// ****************************** update${moduleName} ******************************
// todo: delete this line if you have corrected the dto
export class Update${moduleName}BodyDto extends PartialType(Create${moduleName}BodyDto) {
  // User OmitType if needed
}

export class Update${moduleName}ResponseDto extends Base${moduleName}ResponseDto {}

// ****************************** More dto below ******************************
`;
}
