import { PartialType } from '@nestjs/swagger';
import { Gender, UserLanguage, UserRole, UserStatus } from '@prisma/client';
import { DatabaseModelFields } from '@server/libs/database';
import { PaginationMetadataResponseDto, PaginationQueryDto } from '@server/platform/dtos';
import { IsEmail } from 'class-validator';
import { MultipleOrderBy, PropertyDto } from 'src/decorator';

// Auto generated by tools/generate-dtos.ts at 2026-02-17T14:57:18.888Z
// ****************************** BASE User RESPONSE ******************************
export class BaseUserResponseDto {
  @PropertyDto()
  id: number;

  @PropertyDto()
  email: string;

  @PropertyDto()
  firstName: string;

  @PropertyDto()
  lastName: string;

  @PropertyDto()
  fullName: string;

  @PropertyDto()
  phoneNumber: string;

  @PropertyDto()
  status: UserStatus;

  @PropertyDto()
  dob: Date;

  @PropertyDto()
  role: UserRole;

  @PropertyDto()
  gender: Gender;

  @PropertyDto()
  address: string;

  @PropertyDto()
  city: string;

  @PropertyDto()
  country: string;

  @PropertyDto()
  imageLink: string;

  @PropertyDto()
  lastActive: Date;

  @PropertyDto()
  language: UserLanguage;
}

// ****************************** getUserDetail ******************************
export class GetUserDetailResponseDto extends BaseUserResponseDto {
  // Add more fields if needed such as relations
}

// ****************************** getUserList ******************************
export class GetUserItemDto extends BaseUserResponseDto {
  // Add more fields if needed such as relations
}

export class GetUserListResponseDto {
  @PropertyDto({
    type: GetUserItemDto,
    structure: 'dtoArray',
  })
  items: GetUserItemDto[];

  @PropertyDto({
    type: PaginationMetadataResponseDto,
    structure: 'dto',
  })
  pagination: PaginationMetadataResponseDto;
}

export class GetUserListQueryDto extends PaginationQueryDto {
  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  id: number;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  email: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  password: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  fullName: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  phoneNumber: string;

  @PropertyDto({
    type: UserStatus,
    required: false,
    validated: true,
    structure: 'enum',
  })
  status: UserStatus;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  dobRangeStart: Date;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  dobRangeEnd: Date;

  @PropertyDto({
    type: UserRole,
    required: false,
    validated: true,
    structure: 'enum',
  })
  role: UserRole;

  @PropertyDto({
    type: Gender,
    required: false,
    validated: true,
    structure: 'enum',
  })
  gender: Gender;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  address: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  city: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  country: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  imageLink: string;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  lastActiveRangeStart: Date;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  lastActiveRangeEnd: Date;

  @PropertyDto({
    type: Boolean,
    required: false,
    validated: true,
  })
  forceResetPassword: boolean;

  @PropertyDto({
    type: UserLanguage,
    required: false,
    validated: true,
    structure: 'enum',
  })
  language: UserLanguage;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  createdAtRangeStart: Date;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  createdAtRangeEnd: Date;

  @MultipleOrderBy(DatabaseModelFields.User)
  orderBy: string[];
}

// ****************************** createUser ******************************
export class CreateUserBodyDto {
  @PropertyDto({
    type: String,
    required: true,
    validated: true,
  })
  @IsEmail()
  email: string;

  @PropertyDto({
    type: String,
    required: true,
    validated: true,
  })
  firstName: string;

  @PropertyDto({
    type: String,
    required: true,
    validated: true,
  })
  lastName: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  phoneNumber: string;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  dob: Date;

  @PropertyDto({
    type: UserRole,
    required: true,
    validated: true,
    structure: 'enum',
  })
  role: UserRole;

  @PropertyDto({
    type: Gender,
    required: true,
    validated: true,
    structure: 'enum',
  })
  gender: Gender;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  address: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  city: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  country: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  imageLink: string;

  @PropertyDto({
    type: UserLanguage,
    required: false,
    validated: true,
    structure: 'enum',
  })
  language: UserLanguage;
}

export class CreateUserResponseDto extends BaseUserResponseDto {}

// ****************************** updateUser ******************************
export class UpdateUserBodyDto extends PartialType(CreateUserBodyDto) {
  // User OmitType if needed
}

export class UpdateUserResponseDto extends BaseUserResponseDto {}

// ****************************** More dto below ******************************
