import { PartialType } from '@nestjs/swagger';
import { Languages } from '@prisma/client';
import { DatabaseModelFields } from '@server/libs/database';
import { PaginationQueryDto } from '@server/platform/dtos';
import { MultipleOrderBy, PropertyDto } from 'src/decorator';

// Auto generated by tools/generate-dtos.ts at 2025-10-12T14:01:14.577Z
// ****************************** Base PhraseMeaning response dto ******************************
export class BasePhraseMeaningResponseDto {
  @PropertyDto()
  id: number;

  @PropertyDto()
  key: string;

  @PropertyDto()
  content: string;

  @PropertyDto()
  phraseId: number;

  @PropertyDto()
  language: Languages;

  @PropertyDto()
  createdAt: Date;
}

// ****************************** GET PhraseMeaning dto ******************************
export class GetPhraseMeaningDetailResponseDto extends BasePhraseMeaningResponseDto {
  // Add more fields if needed such as relations
}

export class GetPhraseMeaningListResponseDto extends BasePhraseMeaningResponseDto {
  // Add more fields if needed such as relations
}

export class GetPhraseMeaningListQueryDto extends PaginationQueryDto {
  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  id: number;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  key: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  content: string;

  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  phraseId: number;

  @PropertyDto({
    type: Languages,
    required: false,
    validated: true,
    structure: 'enum',
  })
  language: Languages;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  createdAtRangeStart: Date;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  createdAtRangeEnd: Date;

  @MultipleOrderBy(DatabaseModelFields.PhraseMeaning)
  orderBy: string[];
}

// ****************************** CREATE PhraseMeaning dto ******************************
// todo: delete this line if you have corrected the dto
export class CreatePhraseMeaningBodyDto {
  @PropertyDto({
    type: String,
    required: true,
    validated: true,
  })
  key: string;

  @PropertyDto({
    type: String,
    required: true,
    validated: true,
  })
  content: string;

  @PropertyDto({
    type: Number,
    required: true,
    validated: true,
  })
  phraseId: number;

  @PropertyDto({
    type: Languages,
    required: true,
    validated: true,
    structure: 'enum',
  })
  language: Languages;
}

export class CreatePhraseMeaningResponseDto extends BasePhraseMeaningResponseDto {}

// ****************************** UPDATE PhraseMeaning dto ******************************
// todo: delete this line if you have corrected the dto
export class UpdatePhraseMeaningBodyDto extends PartialType(CreatePhraseMeaningBodyDto) {
  // User OmitType if needed
}

export class UpdatePhraseMeaningResponseDto extends BasePhraseMeaningResponseDto {}

// ****************************** More PhraseMeaning dto below ******************************
