import { PartialType } from '@nestjs/swagger';
import { RedemptionStatus } from '@prisma/client';
import { DatabaseModelFields } from '@server/libs/database';
import { PaginationMetadataResponseDto, PaginationQueryDto } from '@server/platform/dtos';
import { MultipleOrderBy, PropertyDto } from 'src/decorator';

// Auto generated by tools/generate-dtos.ts at 2026-02-14T17:28:16.121Z
// ****************************** BASE Redemption RESPONSE ******************************
export class BaseRedemptionResponseDto {
  @PropertyDto()
  id: number;

  @PropertyDto()
  userId: number;

  @PropertyDto()
  title: string;

  @PropertyDto()
  status: RedemptionStatus;

  @PropertyDto()
  reward: string;

  @PropertyDto()
  description: string;

  @PropertyDto()
  archivedAt: Date;

  @PropertyDto()
  createdAt: Date;
}

// ****************************** getRedemptionDetail ******************************
export class GetRedemptionDetailResponseDto extends BaseRedemptionResponseDto {
  // Add more fields if needed such as relations
}

// ****************************** getRedemptionList ******************************
export class GetRedemptionItemDto extends BaseRedemptionResponseDto {
  // Add more fields if needed such as relations
}

export class GetRedemptionListResponseDto {
  @PropertyDto({
    type: GetRedemptionItemDto,
    structure: 'dtoArray',
  })
  data: GetRedemptionItemDto[];

  @PropertyDto({
    type: PaginationMetadataResponseDto,
    structure: 'dto',
  })
  pagination: PaginationMetadataResponseDto;
}

export class GetRedemptionListQueryDto extends PaginationQueryDto {
  @PropertyDto({
    type: String,
    required: false,
    validated: true,
    description: `Search by title, reward, or description`,
  })
  search: string;

  @PropertyDto({
    type: RedemptionStatus,
    required: false,
    validated: true,
    structure: 'enum',
  })
  status: RedemptionStatus;

  @MultipleOrderBy(DatabaseModelFields.Redemption)
  orderBy: string[];
}

// ****************************** createRedemption ******************************
export class CreateRedemptionBodyDto {
  @PropertyDto({
    type: String,
    required: true,
    validated: true,
  })
  title: string;

  @PropertyDto({
    type: String,
    required: true,
    validated: true,
  })
  reward: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  description: string;
}

export class CreateRedemptionResponseDto extends BaseRedemptionResponseDto {}

// ****************************** updateRedemption ******************************
export class UpdateRedemptionBodyDto extends PartialType(CreateRedemptionBodyDto) {
  @PropertyDto({
    type: RedemptionStatus,
    required: false,
    validated: true,
    structure: 'enum',
  })
  status: RedemptionStatus;
}

export class UpdateRedemptionResponseDto extends BaseRedemptionResponseDto {}

// ****************************** Patch Redemption dto ******************************
export class PatchRedemptionBodyDto {
  @PropertyDto({
    type: RedemptionStatus,
    required: true,
    validated: true,
    structure: 'enum',
  })
  status: RedemptionStatus;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  description?: string;
}

export class PatchRedemptionResponseDto extends BaseRedemptionResponseDto {}
