import { PartialType } from '@nestjs/swagger';
import { RedemptionStatus } from '@prisma/client';
import { DatabaseModelFields } from '@server/libs/database';
import { PaginationQueryDto } from '@server/platform/dtos';
import { MultipleOrderBy, PropertyDto } from 'src/decorator';

// Auto generated by tools/generate-dtos.ts at 2025-12-16T03:47:55.915Z
// ****************************** Base Redemption response dto ******************************
export class BaseRedemptionResponseDto {
  @PropertyDto()
  id: number;

  @PropertyDto()
  userId: number;

  @PropertyDto()
  title: string;

  @PropertyDto()
  status: RedemptionStatus;

  @PropertyDto()
  reward: string;

  @PropertyDto()
  description: string;

  @PropertyDto()
  archivedAt: Date;

  @PropertyDto()
  createdAt: Date;
}

// ****************************** GET Redemption dto ******************************
export class GetRedemptionDetailResponseDto extends BaseRedemptionResponseDto {
  // Add more fields if needed such as relations
}

export class GetRedemptionListResponseDto extends BaseRedemptionResponseDto {
  // Add more fields if needed such as relations
}

export class GetRedemptionListQueryDto extends PaginationQueryDto {
  @PropertyDto({
    type: String,
    required: false,
    validated: true,
    description: `Search by title, reward, or description`,
  })
  search: string;

  @PropertyDto({
    type: RedemptionStatus,
    required: false,
    validated: true,
    structure: 'enum',
  })
  status: RedemptionStatus;

  @MultipleOrderBy(DatabaseModelFields.Redemption)
  orderBy: string[];
}

// ****************************** CREATE Redemption dto ******************************
export class CreateRedemptionBodyDto {
  @PropertyDto({
    type: String,
    required: true,
    validated: true,
  })
  title: string;

  @PropertyDto({
    type: String,
    required: true,
    validated: true,
  })
  reward: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  description: string;
}

export class CreateRedemptionResponseDto extends BaseRedemptionResponseDto {}

// ****************************** UPDATE Redemption dto ******************************
export class UpdateRedemptionBodyDto extends PartialType(CreateRedemptionBodyDto) {
  @PropertyDto({
    type: RedemptionStatus,
    required: false,
    validated: true,
    structure: 'enum',
  })
  status: RedemptionStatus;
}

export class UpdateRedemptionResponseDto extends BaseRedemptionResponseDto {}

// ****************************** Patch Redemption dto ******************************
export class PatchRedemptionBodyDto {
  @PropertyDto({
    type: RedemptionStatus,
    required: true,
    validated: true,
    structure: 'enum',
  })
  status: RedemptionStatus;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  description?: string;
}

export class PatchRedemptionResponseDto extends BaseRedemptionResponseDto {}
