import { PartialType } from '@nestjs/swagger';
import { Languages } from '@prisma/client';
import { DatabaseModelFields } from '@server/libs/database';
import { PaginationQueryDto } from '@server/platform/dtos';
import { MultipleOrderBy, PropertyDto } from 'src/decorator';

// Auto generated by tools/generate-dtos.ts at 2025-10-12T14:00:31.515Z
// ****************************** Base Phrase response dto ******************************
export class BasePhraseResponseDto {
  @PropertyDto()
  id: number;

  @PropertyDto()
  language: Languages;

  @PropertyDto()
  content: string;

  @PropertyDto()
  hint: string;

  @PropertyDto()
  description: string;

  @PropertyDto()
  createdAt: Date;
}

// ****************************** GET Phrase dto ******************************
export class GetPhraseDetailResponseDto extends BasePhraseResponseDto {
  // Add more fields if needed such as relations
}
// ****************************** GET Phrase random dto ******************************

export class GetRandomPhraseResponseDto extends BasePhraseResponseDto {
  // Add more fields if needed such as relations
}
// ****************************** GET Phrase list dto ******************************

export class GetPhraseListResponseDto extends BasePhraseResponseDto {
  // Add more fields if needed such as relations
}

export class GetPhraseListQueryDto extends PaginationQueryDto {
  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  id: number;

  @PropertyDto({
    type: Languages,
    required: false,
    validated: true,
    structure: 'enumArray',
  })
  language: Languages[];

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  content: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  hint: string;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  createdAtRangeStart: Date;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  createdAtRangeEnd: Date;

  @MultipleOrderBy(DatabaseModelFields.Phrase)
  orderBy: string[];
}

// ****************************** CREATE Phrase dto ******************************
export class CreatePhraseBodyDto {
  @PropertyDto({
    type: Languages,
    required: false,
    validated: true,
    structure: 'enum',
  })
  language: Languages;

  @PropertyDto({
    type: String,
    required: true,
    validated: true,
  })
  content: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  hint: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  description: string;
}

export class CreatePhraseResponseDto extends BasePhraseResponseDto {}

// ****************************** UPDATE Phrase dto ******************************
export class UpdatePhraseBodyDto extends PartialType(CreatePhraseBodyDto) {
  // User OmitType if needed
}

export class UpdatePhraseResponseDto extends BasePhraseResponseDto {}

// ****************************** More Phrase dto below ******************************
