import { OmitType, PartialType } from '@nestjs/swagger';

import { PaginationMetadataResponseDto, PaginationQueryDto } from '@server/platform/dtos';
import { DatabaseModelFields } from '@server/libs/database';
import { MultipleOrderBy, PropertyDto } from 'src/decorator';
import { Min, Max } from 'class-validator';

// Auto generated by tools/generate-dtos.ts at 2026-06-22T16:35:32.541Z
// ****************************** BASE PhraseAudioRating RESPONSE ******************************
export class BasePhraseAudioRatingResponseDto {
  @PropertyDto()
  id: number;

  @PropertyDto()
  phraseAudioId: number;

  @PropertyDto()
  rating: number;

  @PropertyDto()
  userId: number;

  @PropertyDto()
  createdAt: Date;

}

// ****************************** getPhraseAudioRatingDetail ******************************
export class GetPhraseAudioRatingDetailResponseDto extends BasePhraseAudioRatingResponseDto {
  // Add more fields if needed such as relations
}

// ****************************** getPhraseAudioRatingList ******************************
export class GetPhraseAudioRatingItemDto extends BasePhraseAudioRatingResponseDto {
  // Add more fields if needed such as relations
}

export class GetPhraseAudioRatingListResponseDto {
  @PropertyDto({
    type: GetPhraseAudioRatingItemDto,
    structure: 'dtoArray',
  })
  items: GetPhraseAudioRatingItemDto[];

  @PropertyDto({
    type: PaginationMetadataResponseDto,
    structure: 'dto',
  })
  pagination: PaginationMetadataResponseDto;
}

export class GetPhraseAudioRatingListQueryDto extends PaginationQueryDto {
  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  id: number;

  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  phraseAudioId: number;

  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  rating: number;

  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  userId: number;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  createdAtRangeStart: Date;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  createdAtRangeEnd: Date;


  @MultipleOrderBy(DatabaseModelFields.PhraseAudioRating)
  orderBy: string[];
  
}

// ****************************** createPhraseAudioRating ******************************
export class CreatePhraseAudioRatingBodyDto {
  @PropertyDto({
    type: Number,
    required: true,
    validated: true,
  })
  phraseAudioId: number;

  @PropertyDto({
    type: Number,
    required: true,
    validated: true,
  })
  @Min(1)
  @Max(10)
  rating: number;
}

export class CreatePhraseAudioRatingResponseDto extends BasePhraseAudioRatingResponseDto {}

// ****************************** updatePhraseAudioRating ******************************
export class UpdatePhraseAudioRatingBodyDto extends PartialType(
  OmitType(CreatePhraseAudioRatingBodyDto, [])
) {}

export class UpdatePhraseAudioRatingResponseDto extends BasePhraseAudioRatingResponseDto {}

// ****************************** More dto below ******************************
