import { PartialType } from '@nestjs/swagger';
import { DatabaseModelFields } from '@server/libs/database';
import { PaginationQueryDto } from '@server/platform/dtos';
import { MultipleOrderBy, PropertyDto } from 'src/decorator';

// Auto generated by tools/generate-dtos.ts at 2026-01-06T12:00:15.824Z
// ****************************** Base PodRegistration response dto ******************************
export class BasePodRegistrationResponseDto {
  @PropertyDto()
  id: number;

  @PropertyDto()
  fullName: string;

  @PropertyDto()
  email: string;

  @PropertyDto()
  phone: string;

  @PropertyDto()
  idea: string;

  @PropertyDto()
  details: string;

  @PropertyDto()
  createdAt: Date;
}

// ****************************** GET PodRegistration dto ******************************
export class GetPodRegistrationDetailResponseDto extends BasePodRegistrationResponseDto {
  // Add more fields if needed such as relations
}

export class GetPodRegistrationListResponseDto extends BasePodRegistrationResponseDto {
  // Add more fields if needed such as relations
}

export class GetPodRegistrationListQueryDto extends PaginationQueryDto {
  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  id: number;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  fullName: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  email: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  phone: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  idea: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  details: string;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  createdAtRangeStart: Date;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  createdAtRangeEnd: Date;

  @MultipleOrderBy(DatabaseModelFields.PodRegistration)
  orderBy: string[];
}

// ****************************** CREATE PodRegistration dto ******************************
export class CreatePodRegistrationBodyDto {
  @PropertyDto({
    type: String,
    required: true,
    validated: true,
  })
  fullName: string;

  @PropertyDto({
    type: String,
    required: true,
    validated: true,
  })
  email: string;

  @PropertyDto({
    type: String,
    required: true,
    validated: true,
  })
  phone: string;

  @PropertyDto({
    type: String,
    required: true,
    validated: true,
  })
  idea: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  details: string;
}

export class CreatePodRegistrationResponseDto extends BasePodRegistrationResponseDto {}

// ****************************** UPDATE PodRegistration dto ******************************
export class UpdatePodRegistrationBodyDto extends PartialType(
  CreatePodRegistrationBodyDto,
) {
  // User OmitType if needed
}

export class UpdatePodRegistrationResponseDto extends BasePodRegistrationResponseDto {}

// ****************************** More PodRegistration dto below ******************************
