import { PartialType } from '@nestjs/swagger';
import { DatabaseModelFields } from '@server/libs/database';
import { PaginationMetadataResponseDto, PaginationQueryDto } from '@server/platform/dtos';
import { IsEmail, MaxLength, MinLength } from 'class-validator';
import { IsVietnamesePhoneNumber, MultipleOrderBy, PropertyDto } from 'src/decorator';

// Auto generated by tools/generate-dtos.ts at 2026-01-06T12:00:15.824Z
// ****************************** Base PodRegistration response dto ******************************
export class BasePodRegistrationResponseDto {
  @PropertyDto()
  id: number;

  @PropertyDto()
  fullName: string;

  @PropertyDto()
  email: string;

  @PropertyDto()
  phone: string;

  @PropertyDto()
  idea: string;

  @PropertyDto()
  details: string;

  @PropertyDto()
  createdAt: Date;
}

// ****************************** GET PodRegistration dto ******************************
export class GetPodRegistrationDetailResponseDto extends BasePodRegistrationResponseDto {
  // Add more fields if needed such as relations
}

export class GetPodRegistrationListResponseDto extends BasePodRegistrationResponseDto {
  // Add more fields if needed such as relations
}

export class GetPodRegistrationListResponse {
  @PropertyDto({
    type: GetPodRegistrationListResponseDto,
    structure: 'dtoArray',
  })
  data: GetPodRegistrationListResponseDto[];

  @PropertyDto({
    type: PaginationMetadataResponseDto,
    structure: 'dto',
  })
  pagination: PaginationMetadataResponseDto;
}

export class GetPodRegistrationListQueryDto extends PaginationQueryDto {
  @PropertyDto({
    type: Number,
    required: false,
    validated: true,
  })
  id: number;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  fullName: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  email: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  phone: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  idea: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
  })
  details: string;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  createdAtRangeStart: Date;

  @PropertyDto({
    type: Date,
    required: false,
    validated: true,
  })
  createdAtRangeEnd: Date;

  @MultipleOrderBy(DatabaseModelFields.PodRegistration)
  orderBy: string[];
}

// ****************************** CREATE PodRegistration dto ******************************
export class CreatePodRegistrationBodyDto {
  @PropertyDto({
    type: String,
    required: true,
    validated: true,
    description: 'Full name of the registrant',
    example: 'Nguyễn Văn A',
  })
  @MinLength(2, { message: 'Full name must be at least 2 characters long' })
  @MaxLength(100, { message: 'Full name must not exceed 100 characters' })
  fullName: string;

  @PropertyDto({
    type: String,
    required: true,
    validated: true,
    description: 'Email address of the registrant',
    example: 'example@email.com',
  })
  @IsEmail({}, { message: 'Email must be a valid email address' })
  email: string;

  @PropertyDto({
    type: String,
    required: true,
    validated: true,
    description: 'Vietnamese phone number (e.g., 0912345678 or +84912345678)',
    example: '0912345678',
  })
  @IsVietnamesePhoneNumber({ message: 'Phone must be a valid Vietnamese phone number' })
  phone: string;

  @PropertyDto({
    type: String,
    required: true,
    validated: true,
    description: 'Brief description of the project idea',
    example: 'Build a mobile app for food delivery',
  })
  @MinLength(10, { message: 'Idea must be at least 10 characters long' })
  @MaxLength(255, { message: 'Idea must not exceed 255 characters' })
  idea: string;

  @PropertyDto({
    type: String,
    required: false,
    validated: true,
    description: 'Detailed description of the project',
    example: 'The app will allow users to order food from restaurants...',
  })
  @MaxLength(5000, { message: 'Details must not exceed 5000 characters' })
  details: string;
}

export class CreatePodRegistrationResponseDto extends BasePodRegistrationResponseDto {}

// ****************************** UPDATE PodRegistration dto ******************************
export class UpdatePodRegistrationBodyDto extends PartialType(
  CreatePodRegistrationBodyDto,
) {
  // User OmitType if needed
}

export class UpdatePodRegistrationResponseDto extends BasePodRegistrationResponseDto {}

// ****************************** More PodRegistration dto below ******************************
